version: '3.7'
services:
  app:
    container_name: simple-react-app
    build: .
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start